# jisho_audio.py
# File Generated by AI
from __future__ import annotations

import os
import re
import urllib.parse

from typing import Optional

import requests
from aqt import mw
from aqt.utils import showInfo


# Jisho search base URL
_JISHO_SEARCH_URL = "https://jisho.org/search/"

# CloudFront audio URL pattern used by Jisho
_AUDIO_PATTERN = re.compile(
    r"//[0-9A-Za-z\-]+\.cloudfront\.net/audio(?:_ogg)?/[0-9A-Za-z]+\.(?:mp3|ogg)"
)


def _find_jisho_audio_url(term: str) -> Optional[str]:
    """
    Fetch the Jisho search page for `term` and return the first audio URL, or None.
    """
    # Jisho expects URL-encoded UTF-8
    query = urllib.parse.quote(term.encode("utf-8"))

    try:
        resp = requests.get(_JISHO_SEARCH_URL + query, timeout=10)
        resp.raise_for_status()
    except Exception as e:
        showInfo(f"Error contacting Jisho for audio: {e}")
        return None

    match = _AUDIO_PATTERN.search(resp.text)
    if not match:
        return None

    url = match.group(0)
    if url.startswith("//"):
        url = "https:" + url
    return url


def _suggest_media_name(term: str, ext: str) -> str:
    """
    Sanitize the term to a safe filename and add the extension.
    """
    # Basic cleanup: replace anything not alnum/underscore/hyphen with underscore
    base = re.sub(r"[^\w\-]+", "_", term)
    base = base.strip("_") or "audio"
    return base + ext


def ensure_audio_in_media(search_term: str) -> Optional[str]:
    """
    Ensure audio for `search_term` is present in the collection's media folder.

    Returns the media filename (to be used in [sound:...]) or None if unavailable.
    """
    audio_url = _find_jisho_audio_url(search_term)
    if not audio_url:
        return None

    # Figure out extension from URL, default to .mp3
    parsed_path = urllib.parse.urlparse(audio_url).path
    _, ext = os.path.splitext(parsed_path)
    if not ext:
        ext = ".mp3"

    desired_name = _suggest_media_name(search_term, ext)

    # Get media directory from collection
    media_dir = mw.col.media.dir()
    full_path = os.path.join(media_dir, desired_name)

    # If the file is already there, just reuse it
    if os.path.exists(full_path):
        return desired_name

    # Download and save
    try:
        resp = requests.get(audio_url, stream=True, timeout=15)
        resp.raise_for_status()
        data = b"".join(chunk for chunk in resp.iter_content(chunk_size=8192))
    except Exception as e:
        showInfo(f"Error downloading audio from Jisho: {e}")
        return None

    try:
        # Let Anki handle writing into the media folder (honors naming rules)
        actual_name = mw.col.media.write_data(desired_name, data)
        return actual_name
    except Exception as e:
        showInfo(f"Error saving audio to media: {e}")
        return None
